version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    volumes:
      - type: bind
        source: .env
        target: /home/node/.env

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: